services:
    phantasos.storage:
        class: Component\Storage\MongoDBStorage
        arguments:
            - @doctrine_mongodb.odm.document_manager
    phantasos.processor:
        class: Component\Processor\Processor
        arguments:
            - @phantasos.storage
    phantasos.preparer:
        class: Component\Preparer\Preparer
        arguments:
            - @phantasos.storage
            - @phantasos.processor
            - @router
