services:
    phantasos.filekey.local:
        class: Component\Storage\FileKey\LocalFileKey
    phantasos.alerter:
        class: Component\Alerter\Alerter
    phantasos.storage:
        class: Component\Storage\MongoDBStorage
        arguments:
            - @doctrine_mongodb.odm.document_manager
            - %phantasos_media_directory%
            - @phantasos.filekey.local
            - @phantasos.alerter
    phantasos.processor_container:
        class: Component\Processor\ProcessorContainer
        arguments:
            - @phantasos.storage
    phantasos.image_processor:
        class: Component\Processor\Processors\ImageProcessor
        tags:
            - { name: phantasos.tag.processor }
    phantasos.pdf_processor:
        class: Component\Processor\Processors\PdfProcessor
        tags:
            - { name: phantasos.tag.processor }
    phantasos.audio_processor:
        class: Component\Processor\Processors\AudioProcessor
        arguments:
            - %phantasos_video_timeout%
            - %phantasos_video_threads%
            - %ffmpeg_binary%
            - %ffprobe_binary%
        tags:
            - { name: phantasos.tag.processor }
    phantasos.video_processor:
        class: Component\Processor\Processors\VideoProcessor
        arguments:
            - @phantasos.audio_processor
            - %phantasos_video_timeout%
            - %phantasos_video_threads%
            - %ffmpeg_binary%
            - %ffprobe_binary%
            - @logger
        tags:
            - { name: phantasos.tag.processor }
    phantasos.word_processor:
        class: Component\Processor\Processors\WordProcessor
        tags:
            - { name: phantasos.tag.processor }
    phantasos.excel_processor:
        class: Component\Processor\Processors\ExcelProcessor
        tags:
            - { name: phantasos.tag.processor }
    phantasos.processor:
        class: Component\Processor\ProcessorConsumer
        arguments:
            - @phantasos.storage
            - @phantasos.processor_container
    phantasos.processor_queuer:
        class: Component\Processor\ProcessorQueuer
        arguments:
            - @phantasos.storage
            - @old_sound_rabbit_mq.process_upload_producer
            - @phantasos.processor_container
    phantasos.preparer:
        class: Component\Preparer\Preparer
        arguments:
            - @phantasos.storage
            - @phantasos.processor_queuer
    phantasos.retrieval:
        class: Component\Retrieval\Retrieval
        arguments:
            - @phantasos.storage
