services:
    tyhand.simple_apikey.storage_config_handler:
        class: TyHand\SimpleApiKeyBundle\Storage\StorageConfigurationHandler
        arguments: [ @container ]
    tyhand.simple_apikey.user_provider:
        class: TyHand\SimpleApiKeyBundle\Security\ApiKeyUserProvider
        arguments: [ @tyhand.simple_apikey.storage_config_handler, %tyhand.simple_apikey.key_name% ]
