services:
    tyhand.simple_apikey.storage_config_handler:
        class: TyHand\SimpleApiKeyBundle\Storage\StorageConfigurationHandler
        arguments:
            - @service_container
    tyhand.simple_apikey.user_provider:
        class: TyHand\SimpleApiKeyBundle\Security\ApiKeyUserProvider
        arguments:
            - @tyhand.simple_apikey.storage_config_handler
            - %tyhand.simple_apikey.key_name%
    tyhand.simple_apikey.generator_manager:
        class: TyHand\SimpleApiKeyBundle\Generator\KeyGeneratorManager
    tyhand.simple_apikey.uuid_keygen:
        class: TyHand\SimpleApiKeyBundle\Generator\UuidKeyGenerator
        tags:
            - { name: tyhand.simple_apikey.keygen, alias: uuid, default: false }
