services:
    tyhand.simple_apikey_mongo_storage.manager_grabber:
        class: TyHand\SimpleApiKeyMongoStorageBundle\Storage\ManagerGrabber
        arguments:
            - @doctrine_mongodb
            - %tyhand.simple_apikey_mongo.manager_name%
    tyhand.simple_apikey_mongo_storage.storage:
        class: TyHand\SimpleApiKeyMongoStorageBundle\Storage\MongoApiKeyStorage
        arguments:
            - @tyhand.simple_apikey_mongo_storage.manager_grabber
